corredores_rioja:
    resource: "@CorredoresRiojaBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
